// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMML-N44P9rGCaazOYRGYoUkuFFpIhZxs',
    appId: '1:124454288171:web:a036981eaa6d2491a3236e',
    messagingSenderId: '124454288171',
    projectId: 't-chat-app-6be55',
    authDomain: 't-chat-app-6be55.firebaseapp.com',
    storageBucket: 't-chat-app-6be55.firebasestorage.app',
    measurementId: 'G-PCQT7LBDMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1B0INDWQ9u_pU4gWcnoYX0UBlWIjYnQ',
    appId: '1:124454288171:android:60310fed562f6d25a3236e',
    messagingSenderId: '124454288171',
    projectId: 't-chat-app-6be55',
    storageBucket: 't-chat-app-6be55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOb-ApjMbXIGqHP4YRu4paaT3BAg_rYk',
    appId: '1:124454288171:ios:114c54462f7f4caea3236e',
    messagingSenderId: '124454288171',
    projectId: 't-chat-app-6be55',
    storageBucket: 't-chat-app-6be55.firebasestorage.app',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOb-ApjMbXIGqHP4YRu4paaT3BAg_rYk',
    appId: '1:124454288171:ios:114c54462f7f4caea3236e',
    messagingSenderId: '124454288171',
    projectId: 't-chat-app-6be55',
    storageBucket: 't-chat-app-6be55.firebasestorage.app',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMML-N44P9rGCaazOYRGYoUkuFFpIhZxs',
    appId: '1:124454288171:web:ae0b812d226486fba3236e',
    messagingSenderId: '124454288171',
    projectId: 't-chat-app-6be55',
    authDomain: 't-chat-app-6be55.firebaseapp.com',
    storageBucket: 't-chat-app-6be55.firebasestorage.app',
    measurementId: 'G-5TGNTWX3GE',
  );
}
